apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "solventa-exp1.fullname" . }}-workload
  labels:
    {{- include "solventa-exp1.labels" . | nindent 4 }}
automountServiceAccountToken: false
