{{- if .Values.wiremock.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "solventa-exp1.fullname" . }}-wiremock
  labels:
    {{- include "solventa-exp1.labels" . | nindent 4 }}
    app.kubernetes.io/component: wiremock
spec:
  type: ClusterIP
  selector:
    {{- include "solventa-exp1.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wiremock
  ports:
    - name: http
      port: {{ .Values.wiremock.service.port }}
      targetPort: http
      protocol: TCP
{{- end }}
